apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cert-manager
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cert-manager
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # type: LoadBalancer
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   namespace: cert-manager
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     # nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     cert-manager.io/cluster-issuer: ca-issuer
# spec:
#   ingressClassName: "nginx"
#   tls:
#   - hosts:
#     - nginx.jananathbanuka.site
#     secretName: jananath-self-signed-cert
#   rules:
#     - host: nginx.jananathbanuka.site
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: nginx
#                 port:
#                   number: 80