apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
spec:
  isCA: true
  secretName: jananath-self-signed-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  dnsNames:
   - nginx.jananathbanuka.site